name: "ðŸš€ Releaser"

on:
  push:
    tags:
      - "*"

env:
  PROJECT_FOLDER: "plugin_qgis_lpo"
  PYTHON_VERSION: 3.9


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Get source code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        cache: "pip"
        cache-dependency-path: "requirements/packaging.txt"
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system requirements
      run: |
        sudo apt update
        sudo apt install qt5-qmake qttools5-dev-tools

    - name: Install Python requirements
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements/packaging.txt

    - name: Compile translations
      run: lrelease ${{ env.PROJECT_FOLDER }}/resources/i18n/*.ts

    - name : Get current changelog for ${GITHUB_REF/refs\/tags\//}
      run: qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} >> release.md

    - name: Create release on GitHub
      uses: ncipollo/release-action@v1.14.0
      with:
        bodyFile: release.md
        generateReleaseNotes: true

    - name: Deploy plugin
      run: >-
        echo ${GITHUB_REF/refs\/tags\//} && qgis-plugin-ci
        release ${GITHUB_REF/refs\/tags\//}
        --github-token ${{ secrets.GITHUB_TOKEN }}
        --allow-uncommitted-changes
        --create-plugin-repo
